site_name: SmartWalk Docs
repo_url: https://github.com/zhukovdm/smartwalk-docs
edit_uri: blob/main/content/

docs_dir: content
theme: readthedocs

markdown_extensions:
  - admonition

extra_javascript:
  - js/extra.js

nav:
  - Home: index.md
  - User's documentation: usr.md
  - Programmer's guide: prg.md
  - Administrator's guide: adm.md

use_directory_urls: false
