site_name: SmartWalk Docs
docs_dir: content
theme: readthedocs
markdown_extensions:
  - admonition
nav:
  - Home: index.md
  - User documentation: usr.md
  - Developer manual: dev.md
  - Administrator guide: adm.md
