var searchData=
[
  ['iadvicecontext_2ecs_526',['IAdviceContext.cs',['../IAdviceContext_8cs.html',1,'']]],
  ['idistancematrix_2ecs_527',['IDistanceMatrix.cs',['../IDistanceMatrix_8cs.html',1,'']]],
  ['ientitycontext_2ecs_528',['IEntityContext.cs',['../IEntityContext_8cs.html',1,'']]],
  ['ientityindex_2ecs_529',['IEntityIndex.cs',['../IEntityIndex_8cs.html',1,'']]],
  ['ientitystore_2ecs_530',['IEntityStore.cs',['../IEntityStore_8cs.html',1,'']]],
  ['ifheuristic_2ecs_531',['IfHeuristic.cs',['../IfHeuristic_8cs.html',1,'']]],
  ['ifsolver_2ecs_532',['IfSolver.cs',['../IfSolver_8cs.html',1,'']]],
  ['ikeywordsadvicer_2ecs_533',['IKeywordsAdvicer.cs',['../IKeywordsAdvicer_8cs.html',1,'']]],
  ['iosrmroutefetcher_2ecs_534',['IOsrmRouteFetcher.cs',['../IOsrmRouteFetcher_8cs.html',1,'']]],
  ['iosrmtablefetcher_2ecs_535',['IOsrmTableFetcher.cs',['../IOsrmTableFetcher_8cs.html',1,'']]],
  ['iprecedencematrix_2ecs_536',['IPrecedenceMatrix.cs',['../IPrecedenceMatrix_8cs.html',1,'']]],
  ['iqueryhandler_2ecs_537',['IQueryHandler.cs',['../IQueryHandler_8cs.html',1,'']]],
  ['iqueryparser_2ecs_538',['IQueryParser.cs',['../IQueryParser_8cs.html',1,'']]],
  ['iroutingengine_2ecs_539',['IRoutingEngine.cs',['../IRoutingEngine_8cs.html',1,'']]],
  ['isearchcontext_2ecs_540',['ISearchContext.cs',['../ISearchContext_8cs.html',1,'']]],
  ['isolver_2ecs_541',['ISolver.cs',['../ISolver_8cs.html',1,'']]],
  ['ivalidationresult_2ecs_542',['IValidationResult.cs',['../IValidationResult_8cs.html',1,'']]]
];
